SELECT * FROM V$SYSSTAT;

SELECT
       y.name, s.VALUE "SESSION", y.VALUE "SYSTEM"
FROM V$SESSTAT s
    LEFT JOIN V$SYSSTAT y USING("STATISTIC#") WHERE SID = userenv('SID');

SELECT METRIC_NAME, value, METRIC_UNIT FROM V$SYSMETRIC;

SELECT METRIC_NAME, VALUE, METRIC_UNIT FROM V$SYSMETRIC_HISTORY;

-- Physical Write Total Bytes Per Sec:
SELECT
    TO_CHAR(BEGIN_TIME, 'HH:MM:ss') von,
    TO_CHAR(END_TIME, 'HH:MM:ss') bis,
    METRIC_NAME name,
       ROUND(VALUE, 3) wert,
       METRIC_UNIT
FROM V$SYSMETRIC_HISTORY
WHERE
      METRIC_ID = 2124
ORDER BY BEGIN_TIME;
